apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
      - env:
        - name: NAUTOBOT_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_ALLOWED_HOSTS
              name: postgres-dev-env
        - name: NAUTOBOT_CHANGELOG_RETENTION
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_CHANGELOG_RETENTION
              name: postgres-dev-env
        - name: NAUTOBOT_CONFIG
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_CONFIG
              name: postgres-dev-env
        - name: NAUTOBOT_DB_ENGINE
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_DB_ENGINE
              name: postgres-dev-env
        - name: NAUTOBOT_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_DB_HOST
              name: postgres-dev-env
        - name: NAUTOBOT_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_DB_NAME
              name: postgres-dev-env
        - name: NAUTOBOT_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_DB_PASSWORD
              name: postgres-dev-env
        - name: NAUTOBOT_DB_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_DB_TIMEOUT
              name: postgres-dev-env
        - name: NAUTOBOT_DB_USER
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_DB_USER
              name: postgres-dev-env
        - name: NAUTOBOT_MAX_PAGE_SIZE
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_MAX_PAGE_SIZE
              name: postgres-dev-env
        - name: NAUTOBOT_NAPALM_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_NAPALM_TIMEOUT
              name: postgres-dev-env
        - name: NAUTOBOT_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_REDIS_HOST
              name: postgres-dev-env
        - name: NAUTOBOT_REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_REDIS_PASSWORD
              name: postgres-dev-env
        - name: NAUTOBOT_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_REDIS_PORT
              name: postgres-dev-env
        - name: NAUTOBOT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_SECRET_KEY
              name: postgres-dev-env
        - name: NAUTOBOT_SELENIUM_HOST
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_SELENIUM_HOST
              name: postgres-dev-env
        - name: NAUTOBOT_SELENIUM_URL
          valueFrom:
            configMapKeyRef:
              key: NAUTOBOT_SELENIUM_URL
              name: postgres-dev-env
        - name: PGPASSWORD
          valueFrom:
            configMapKeyRef:
              key: PGPASSWORD
              name: postgres-dev-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-dev-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-dev-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-dev-env
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: REDIS_PASSWORD
              name: postgres-dev-env
        image: postgres:13
        name: postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata-nautobot
      restartPolicy: Always
      volumes:
      - name: pgdata-nautobot
        persistentVolumeClaim:
          claimName: pgdata-nautobot
status: {}
